// Circuit geometry: centreline samples, altitude, curvature, speed limits, zones (tunnel, pits, chicane,
// Sainte Dévote, start straight), centreline-point lookups (cpIdx) and the sea/green masks from OpenStreetMap.

import {lerp,pip,sstep,wrapA} from './util.js';

// ---------------------------------------------------------------- track data: official centreline (GPS, projected to metres; x = east, y = north)
// map data generated by tools/prep.py; fetched before anything else is built (every importer waits for it)
async function loadMapData(){
 try{const res=await fetch(new URL('../data/monaco.json',import.meta.url));if(!res.ok)throw new Error('HTTP '+res.status);return await res.json();}
 catch(err){const el=document.getElementById('loading');if(el)el.textContent='No se pudieron cargar los datos del mapa (data/monaco.json): '+err.message+'. Recargá la página para reintentar.';throw err;}}
const DATA=await loadMapData();
const HW=5.2;
const TP=DATA.track;
// altitude anchors by centreline point (m above sea): 42 m of climb, top at Casino Square (T4), bottom just before La Rascasse
const HA=[[0,44.8],[3,44.5],[5,43.4],[6,38.6],[10,35.6],[14,32.2],[18,28.8],[22,26.6],[26,25.2],[29,22.2],[33,17],[37,12.6],[39,11.6],[40,11.1],[43,9.6],[45,8.6],[46,8],[48,6.5],[50,5],[52,3.9],[55,3.4],[64,3.1],[80,2.8],[92,2.5],[95,2.35],[99,2.45],[104,2.7],[110,3.2],[113,3.8],[116,4.4],[119,5],[122,5.4],[125,5.9],[128,7.2],[131,9.2],[134,13],[137,20.5],[140,27],[143,33.6],[146,37.8],[149,41.4],[152,43.4],[155,44.3],[158,44.8]];
const TPS=[0];for(let i=1;i<TP.length;i++)TPS.push(TPS[i-1]+Math.hypot(TP[i][0]-TP[i-1][0],TP[i][1]-TP[i-1][1]));
function tpH(k){for(let a=0;a<HA.length-1;a++){const [i0,h0]=HA[a],[i1,h1]=HA[a+1];if(k>=i0&&k<=i1){const t=(TPS[k]-TPS[i0])/Math.max(1e-6,TPS[i1]-TPS[i0]);return lerp(h0,h1,t);}}return HA[HA.length-1][1];}
const W=(x,y)=>[x,-y]; // local metres -> world X,Z
const curve=new THREE.CatmullRomCurve3(TP.map((p,k)=>new THREE.Vector3(p[0],tpH(k),-p[1])),true,'centripetal');
const LEN=curve.getLength();
const N=Math.round(LEN/2), DS=LEN/N;
let raw=curve.getSpacedPoints(N);raw.pop();
const START_CP=119;
{let bi=0,bd=1e18;const sx=TP[START_CP][0],sz=-TP[START_CP][1];raw.forEach((p,i)=>{const d=(p.x-sx)**2+(p.z-sz)**2;if(d<bd){bd=d;bi=i;}});raw=raw.slice(bi).concat(raw.slice(0,bi));}
const SX=new Float32Array(N),SY=new Float32Array(N),SZ=new Float32Array(N),TXa=new Float32Array(N),TZa=new Float32Array(N),RXa=new Float32Array(N),RZa=new Float32Array(N),PSI=new Float32Array(N),K=new Float32Array(N),ALLOW=new Float32Array(N);
const TUN=new Uint8Array(N),PIT=new Uint8Array(N);
for(let i=0;i<N;i++){SX[i]=raw[i].x;SY[i]=raw[i].y;SZ[i]=raw[i].z;}
const mod=i=>((i%N)+N)%N;
for(let pass=0;pass<3;pass++){const t=SY.slice();for(let i=0;i<N;i++){let s=0;for(let k=-7;k<=7;k++)s+=t[mod(i+k)];SY[i]=s/15;}}
for(let i=0;i<N;i++){const a=mod(i-1),b=mod(i+1);let tx=SX[b]-SX[a],tz=SZ[b]-SZ[a];const l=Math.hypot(tx,tz);tx/=l;tz/=l;TXa[i]=tx;TZa[i]=tz;RXa[i]=-tz;RZa[i]=tx;PSI[i]=Math.atan2(-tx,-tz);}
{const k0=new Float32Array(N);for(let i=0;i<N;i++)k0[i]=wrapA(PSI[mod(i+3)]-PSI[mod(i-3)])/(6*DS);for(let i=0;i<N;i++){let s=0;for(let k=-3;k<=3;k++)s+=k0[mod(i+k)];K[i]=s/7;}}
{const AY=25,B=28,VMAX=86;for(let i=0;i<N;i++)ALLOW[i]=Math.min(VMAX,Math.sqrt(AY/Math.max(Math.abs(K[i]),1e-4)));for(let rep=0;rep<2;rep++)for(let i=N-1;i>=0;i--){const n=ALLOW[mod(i+1)];ALLOW[i]=Math.min(ALLOW[i],Math.sqrt(n*n+2*B*DS));}}
// spatial hash of samples
const HC=20,HASH=new Map();
for(let i=0;i<N;i++){const key=Math.floor(SX[i]/HC)+','+Math.floor(SZ[i]/HC);if(!HASH.has(key))HASH.set(key,[]);HASH.get(key).push(i);}
function nearest(X,Z,maxR){const r=Math.ceil(maxR/HC),cx=Math.floor(X/HC),cz=Math.floor(Z/HC);let bd=maxR*maxR,bi=-1;for(let a=-r;a<=r;a++)for(let b=-r;b<=r;b++){const arr=HASH.get((cx+a)+','+(cz+b));if(!arr)continue;for(const i of arr){const d=(SX[i]-X)**2+(SZ[i]-Z)**2;if(d<bd){bd=d;bi=i;}}}return bi<0?null:{i:bi,d:Math.sqrt(bd)};}
// highest the ground may be at a point: never above any nearby stretch of road (checks every branch, e.g. both sides of the hairpin)
function roadCap(X,Z,R){const r=Math.ceil(R/HC),cx=Math.floor(X/HC),cz=Math.floor(Z/HC);let cap=1e9;for(let a=-r;a<=r;a++)for(let b=-r;b<=r;b++){const arr=HASH.get((cx+a)+','+(cz+b));if(!arr)continue;for(const i of arr){const d=Math.hypot(SX[i]-X,SZ[i]-Z);if(d>R)continue;cap=Math.min(cap,SY[i]-0.35+Math.max(0,d-(HW+10+EXMAX(i)))*2.2);}}return cap;}
function roadMin(X,Z,R){const r=Math.ceil(R/HC),cx=Math.floor(X/HC),cz=Math.floor(Z/HC);let mn=1e9;for(let a=-r;a<=r;a++)for(let b=-r;b<=r;b++){const arr=HASH.get((cx+a)+','+(cz+b));if(!arr)continue;for(const i of arr){if((SX[i]-X)**2+(SZ[i]-Z)**2<R*R)mn=Math.min(mn,SY[i]);}}return mn;}
function rangeIdx(a,b){const out=[];let i=a;while(true){out.push(i);if(i===b)break;i=mod(i+1);}return out;}
// centreline point k -> sample index (search near its expected arc position, so hairpins never snap to the wrong branch)
function cpIdx(k){const sRel=((TPS[k]-TPS[START_CP])%TPS[TPS.length-1]+TPS[TPS.length-1])%TPS[TPS.length-1];const guess=Math.round(sRel/TPS[TPS.length-1]*N);const X=TP[k][0],Z=-TP[k][1];let bi=guess,bd=1e18;for(let o=-60;o<=60;o++){const i=mod(guess+o);const d=(SX[i]-X)**2+(SZ[i]-Z)**2;if(d<bd){bd=d;bi=i;}}return bi;}
function idxXY(x,y,k){const X=x,Z=-y;const g=cpIdx(k);let bi=g,bd=1e18;for(let o=-80;o<=80;o++){const i=mod(g+o);const d=(SX[i]-X)**2+(SZ[i]-Z)**2;if(d<bd){bd=d;bi=i;}}return bi;}
const CORNERS=[[119,'Recta de boxes','S/F'],[129,'Sainte Dévote','T1'],[133,'Beau Rivage','T2'],[146,'Massenet','T3'],[156,'Casino','T4'],[7,'Mirabeau Haute','T5'],[17,'Horquilla Fairmont','T6'],[26,'Mirabeau Bas','T7'],[32,'Portier','T8'],[39,'El túnel','T9'],[52,'Nouvelle Chicane','T10'],[62,'Tabac','T12'],[72,'Piscine','T13'],[81,'Piscine','T15'],[95,'La Rascasse','T17'],[104,'Anthony Noghès','T19']];
const CPI=CORNERS.map(c=>cpIdx(c[0]));
rangeIdx(idxXY(390,470,39),idxXY(282,187,46)).forEach(i=>TUN[i]=1);
rangeIdx(cpIdx(112),cpIdx(127)).forEach(i=>PIT[i]=1);
const P=(i,d,h)=>[SX[i]+RXa[i]*d,SY[i]+(h||0),SZ[i]+RZa[i]*d];
// Nouvelle Chicane has no armco next to the kerbs: open asphalt run-off on both sides, polystyrene blocks further out
const EXA=[new Float32Array(N),new Float32Array(N)];
const CHI=new Uint8Array(N);const STR=new Uint8Array(N);
{const r=rangeIdx(mod(cpIdx(52)-6),cpIdx(57));const L=r.length;const raw=[new Float32Array(N),new Float32Array(N)];
 r.forEach((i,k)=>{CHI[i]=1;const t=Math.min(1,k/8,(L-1-k)/8);const e=sstep(0,1,t);let kk=0;for(let q=-6;q<=6;q++)kk+=K[mod(i+q)];raw[0][i]=8*e;raw[1][i]=8*e;});
 for(const sd of[0,1])for(const i of r){let a=0,n=0;for(let q=-6;q<=6;q++){a+=raw[sd][mod(i+q)];n++;}EXA[sd][i]=a/n;}}
rangeIdx(cpIdx(104),cpIdx(131)).forEach(i=>STR[i]=1);
const SDZ=new Uint8Array(N);let SD_OUT=0;
{const r=rangeIdx(mod(cpIdx(127)-2),mod(cpIdx(131)+2));let kk=0;r.forEach(i=>kk+=K[i]);SD_OUT=kk>0?1:0;const L=r.length;
 r.forEach((i,k)=>{SDZ[i]=1;const t=Math.min(1,k/7,(L-1-k)/7);EXA[SD_OUT][i]=Math.max(EXA[SD_OUT][i],10*sstep(0,1,t));});}
const EXMAX=i=>Math.max(EXA[0][i],EXA[1][i]);
// Nouvelle Chicane escape road: straight on from the tunnel exit past turn 10, then a left curve that rejoins the
// harbour road after turn 11 (cars that miss the chicane go this way). ESC = centreline points [x, z, y].
const ESC_W=12;
const ESC=(()=>{const a=mod(cpIdx(52)-9),j=mod(cpIdx(57)+11);const tx=TXa[a],tz=TZa[a];
 const L=Math.abs((SX[j]+12-SX[a])/tx); // the straight ends 12 m short (east) of the rejoin point
 const pts=[];for(let s=0;s<=L;s+=4)pts.push([SX[a]+tx*s,SZ[a]+tz*s]);
 const e=[SX[a]+tx*L,SZ[a]+tz*L],c=[e[0]+tx*12,e[1]+tz*12];
 for(let k=1;k<=10;k++){const t=k/10;pts.push([(1-t)**2*e[0]+2*(1-t)*t*c[0]+t*t*SX[j],(1-t)**2*e[1]+2*(1-t)*t*c[1]+t*t*SZ[j]]);}
 // level with the road where they overlap, just under it so the track surface stays on top
 return pts.map((p,k)=>{const n=nearest(p[0],p[1],30);const y=lerp(SY[a],SY[j],k/(pts.length-1));return [p[0],p[1],(n?Math.min(y,SY[n.i]):y)-.03];});})();
// distance from (x, z) to the escape road centreline, with the nearest point, its height and direction
function escAt(x,z){let best=1e9,bk=0,bt=0;for(let k=0;k<ESC.length-1;k++){const A=ESC[k],B=ESC[k+1];const dx=B[0]-A[0],dz=B[1]-A[1];const t=Math.max(0,Math.min(1,((x-A[0])*dx+(z-A[1])*dz)/(dx*dx+dz*dz)));const d=Math.hypot(A[0]+dx*t-x,A[1]+dz*t-z);if(d<best){best=d;bk=k;bt=t;}}
 const A=ESC[bk],B=ESC[bk+1],l=Math.hypot(B[0]-A[0],B[1]-A[1]);return {d:best,x:lerp(A[0],B[0],bt),z:lerp(A[1],B[1],bt),y:lerp(A[2],B[2],bt),dx:(B[0]-A[0])/l,dz:(B[1]-A[1])/l};}
// masks from OpenStreetMap: sea/harbour and green areas (run-length rows, 4 m cells, south to north)
const [GX0,GY0,GC,GNX,GNY]=DATA.grid;
function unrle(r){const m=new Uint8Array(GNX*GNY);r.forEach((row,j)=>{let x=0,v=0;for(const c of row){if(v)m.fill(1,j*GNX+x,j*GNX+x+c);x+=c;v^=1;}});return m;}
const SEA=unrle(DATA.sea),GREEN=unrle(DATA.green);
// Mareterra (Le Portier): 6 ha of land reclaimed east of Portier and unveiled in 2024, newer than the OSM extract,
// so it is cut out of the sea here; its eastern half is the public park (local metres, x = east, y = north)
const MARETERRA=[[395,440],[540,420],[640,455],[700,540],[690,630],[610,690],[470,700],[430,560]];
const MARETERRA_PARK=[[580,440],[640,455],[700,540],[690,630],[610,690],[575,600]];
for(let j=0;j<GNY;j++)for(let i=0;i<GNX;i++){const x=GX0+(i+.5)*GC,y=GY0+(j+.5)*GC;if(!pip(MARETERRA,x,y))continue;SEA[j*GNX+i]=0;if(pip(MARETERRA_PARK,x,y))GREEN[j*GNX+i]=1;}
function maskAt(m,X,Z){const i=Math.floor((X-GX0)/GC),j=Math.floor((-Z-GY0)/GC);if(i<0||j<0||i>=GNX||j>=GNY)return m===SEA?(Z>0?1:0):0;return m[j*GNX+i];}
function isWaterXZ(X,Z){return maskAt(SEA,X,Z)===1;}
function runs(pred){const f=[];for(let i=0;i<N;i++)f.push(!!pred(i));if(f.every(x=>x))return[[0,N]];const s0=f.indexOf(false);const out=[];let st=-1;
 for(let k=1;k<=N;k++){const i=(s0+k)%N;if(f[i]){if(st<0)st=k;}else if(st>=0){out.push([(s0+st)%N,k-1-st]);st=-1;}}return out;}

export {ALLOW,CHI,CORNERS,CPI,DATA,DS,ESC,ESC_W,EXA,EXMAX,GREEN,HW,K,MARETERRA_PARK,N,P,PIT,PSI,RXa,RZa,SDZ,STR,SX,SY,SZ,TUN,TXa,TZa,cpIdx,escAt,isWaterXZ,maskAt,mod,nearest,rangeIdx,roadCap,roadMin,runs};
